version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: fullstack-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fullstack_app
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fullstack-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: fullstack-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/fullstack_app?authSource=admin
      JWT_SECRET: dev-super-secret-jwt-key-256-bits-long
      JWT_REFRESH_SECRET: dev-super-secret-refresh-key-256-bits-long
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_EXPIRES_IN: 30d
      FRONTEND_URL: http://localhost:3000
      ADMIN_URL: http://localhost:3001
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - fullstack-network
    command: ["npm", "run", "dev"]

  # Client Frontend
  client:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile.dev
    container_name: fullstack-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: Fullstack App
      VITE_APP_VERSION: 1.0.0
      VITE_ENVIRONMENT: development
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fullstack-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Admin Dashboard
  admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile.dev
    container_name: fullstack-admin
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: Admin Dashboard
      VITE_APP_VERSION: 1.0.0
      VITE_ENVIRONMENT: development
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - fullstack-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: fullstack-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fullstack-network

volumes:
  mongodb_data:
  redis_data:

networks:
  fullstack-network:
    driver: bridge
